import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Float, Stars } from '@react-three/drei';
import * as THREE from 'three';
import { useEffect, useMemo, useRef } from 'react';
function Peaks(){
 const group=useRef<THREE.Group>(null!); useFrame(({pointer})=>{group.current.rotation.y=THREE.MathUtils.lerp(group.current.rotation.y,pointer.x*.08,.025);group.current.rotation.x=THREE.MathUtils.lerp(group.current.rotation.x,-pointer.y*.025,.025)});
 const peaks=useMemo(()=>Array.from({length:11},(_,i)=>({x:(i%6-2.5)*2.8,z:-Math.floor(i/6)*3.5-2,s:1.3+((i*37)%10)/12,h:2.2+((i*19)%14)/8})),[]);
 const geometry=useMemo(()=>{const radial=18;const rings=7;const positions:number[]=[];const colors:number[]=[];for(let ring=0;ring<=rings;ring++){const t=ring/rings;const radius=Math.max(.08,1-t)*1.05;for(let slice=0;slice<radial;slice++){const a=(slice/radial)*Math.PI*2;const wobble=1+Math.sin(slice*2.7+ring*1.8)*.12;positions.push(Math.cos(a)*radius*wobble,t*2.8,Math.sin(a)*radius*wobble);const snow=Math.max(0,t-.48)/.52;const color=new THREE.Color().lerpColors(new THREE.Color('#38566a'),new THREE.Color('#eef6f8'),snow);colors.push(color.r,color.g,color.b)}}const indices:number[]=[];for(let ring=0;ring<rings;ring++)for(let slice=0;slice<radial;slice++){const n=(slice+1)%radial;const a=ring*radial+slice;const b=ring*radial+n;const c=(ring+1)*radial+slice;const d=(ring+1)*radial+n;indices.push(a,c,b,b,c,d)}const buffer=new THREE.BufferGeometry();buffer.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));buffer.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));buffer.setIndex(indices);buffer.computeVertexNormals();return buffer},[]);
 return <group ref={group} position={[0,-2.1,0]}>{peaks.map((p,i)=><mesh key={i} geometry={geometry} position={[p.x,p.h*.2,p.z]} scale={[p.s,p.h,p.s]}><meshStandardMaterial vertexColors roughness={.92} metalness={.02}/></mesh>)}<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.05,-5]}><planeGeometry args={[40,40,20,20]}/><meshStandardMaterial color="#c5d8df" roughness={1}/></mesh></group>
}
function Snow(){const ref=useRef<THREE.Points>(null!);const positions=useMemo(()=>{const a=new Float32Array(900*3);for(let i=0;i<a.length;i+=3){a[i]=(Math.random()-.5)*26;a[i+1]=Math.random()*14-3;a[i+2]=-Math.random()*24+4}return a},[]);useFrame((_,d)=>{ref.current.rotation.y+=d*.006;ref.current.position.y-=d*.08;if(ref.current.position.y<-1)ref.current.position.y=0});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/></bufferGeometry><pointsMaterial size={.028} color="#ffffff" transparent opacity={.65}/></points>}
function Aurora(){const ref=useRef<THREE.Mesh>(null!);useFrame(({clock})=>{(ref.current.material as THREE.MeshBasicMaterial).opacity=.09+Math.sin(clock.elapsedTime*.35)*.025;ref.current.rotation.z=Math.sin(clock.elapsedTime*.12)*.04});return <mesh ref={ref} position={[0,4,-9]} rotation={[0,0,-.18]}><planeGeometry args={[22,7]}/><meshBasicMaterial color="#19c8e5" transparent opacity={.1} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh>}
 function Clouds(){const group=useRef<THREE.Group>(null!);useFrame((_,delta)=>{group.current.position.x+=delta*.025;if(group.current.position.x>5)group.current.position.x=-5});return <group ref={group} position={[0,-.8,0]}>{Array.from({length:12},(_,i)=><mesh key={i} position={[(i%4-1.5)*2.5,(i%3)*.28,(Math.floor(i/4)-1)*2.8]} scale={[1.8+((i*13)%7)/7,.42+((i*17)%4)/10,.8]}><sphereGeometry args={[1,16,8]}/><meshStandardMaterial color="#f5fbfc" transparent opacity={.25} depthWrite={false} roughness={1}/></mesh>)}</group>}
function ScrollCamera(){const {camera}=useThree();const progress=useRef(0);useEffect(()=>{const update=()=>{const max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight);progress.current=Math.min(1,Math.max(0,window.scrollY/max))};update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);useFrame(({pointer})=>{const p=progress.current;const targetX=pointer.x*.35+Math.sin(p*Math.PI*2)*.7;const targetY=2.6+p*1.25+pointer.y*.15;const targetZ=8-p*3.2;camera.position.x=THREE.MathUtils.lerp(camera.position.x,targetX,.035);camera.position.y=THREE.MathUtils.lerp(camera.position.y,targetY,.035);camera.position.z=THREE.MathUtils.lerp(camera.position.z,targetZ,.035);camera.lookAt(Math.sin(p*Math.PI)*.8,-1.1-p*.4,-4-p*2)});return null}
 export default function PolarScene(){return <Canvas dpr={[1,1.6]} camera={{position:[0,2.6,8],fov:52}} gl={{antialias:true,alpha:true}}><color attach="background" args={['#dce9ed']}/><fog attach="fog" args={['#dce9ed',8,26]}/><ambientLight intensity={1.5}/><directionalLight position={[4,8,4]} intensity={4.2} color="#ffffff"/><directionalLight position={[-6,3,-2]} intensity={1.1} color="#6eabc1"/><ScrollCamera/><Aurora/><Float speed={.35} rotationIntensity={.06} floatIntensity={.08}><Peaks/></Float><Clouds/><Snow/></Canvas>}
